# Generated by Django 5.2.3 on 2025-06-15 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('county', models.CharField(max_length=100, verbose_name='County/Region')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('square_footage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Square Footage')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Landlord')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-date_posted'],
            },
        ),
    ]
