# Generated by Django 5.2.3 on 2025-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/', verbose_name='Main Image'),
        ),
    ]
